#!/usr/bin/env bash
set -e
src=$1
pair=${2/:/}

if [[ ${#2} -eq 6 ]]; then
  base=${pair:0:3}
  quote=${pair:3:6}
else
  base=${2%:*}
  quote=${2#*:}
fi

case $src in
  craft) {
    json=$(curl -sS "http://localhost:3000/dev/craft?company=${base}")
    echo "$(jshon <<<"$json" -e valuation -u)"
  };;
  *) {
    echo >&2 "Error: exchange not recognised: $src"
  };;
esac
